### ISSUE TITLE
Statsページのスキンが1.8表示されていない

### ISSUE THREAD

**Issue by Lizari** [Atria-Network/Atria-Network.github.io#6]
Example
- https://cravatar.eu/helmhead/e11c90e4-7b40-43be-83c2-ca4f9512f6f6/64.png

https://github.com/Atria-Network/Atria-Network.github.io/blob/c85d487622b431c850aa7dcd7c0fd6a29fdc45bb/pages/user/_name.vue#L118

**Comment by yugorbit** [comment]
修正します👍

**Comment by yugorbit** [comment]
修正しました
